### ISSUE TITLE
module 'cv2.cv2' has no attribute 'xfeatures2d'

### ISSUE THREAD

**Issue by Ars235** [HeatherJiaZG/SuperGlue-pytorch#13]
Hi! I was trying to run the training,  but got the following error. Maybe someone encountered this before?
![Screenshot (76)](https://user-images.githubusercontent.com/55205393/101728041-b9331380-3ac6-11eb-97cb-9df8fead8970.png)

**Comment by archershot** [comment]
new version of cv2 has move sift to main repository.
you can change cv2.xfeatures2d.SIFT_create to cv2.SIFT_create
