### ISSUE TITLE
Where can I get MSCOCO2014_yingxin dataset?

### ISSUE THREAD

**Issue by vinhtq115** [HeatherJiaZG/SuperGlue-pytorch#7]
Hi, can you tell me where can I download this dataset? I'm trying to figure out how to run the train.py but cannot find that dataset online.

**Comment by HeatherJiaZG** [comment]
Hi, you can find the dataset at https://cocodataset.org/#download

**Comment by ZhouAo-ZA** [comment]
@HeatherJiaZG Thank you for your share, I have run your train code on coco2014, but I don't know how to evaluate; How can I verify the model after training, using the COCO data set, then I can’t use match_pair to verify, how can I know the precision?
